[project]
name = "dm-research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Suman Phuyal", email = "sfuyal59@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "torch>=2.0.0",
    "torchvision>=0.15.0",
    "timm>=0.9.0",
    "fvcore",
    "ptflops",
    "pandas",
    "matplotlib",
    "seaborn",
    "kaggle",
    "scikit-learn",
    "tqdm"
]

[project.scripts]
dm-research = "dm_research:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu121" }
torchvision = { index = "pytorch-cu121" }
